### ISSUE TITLE
Write JUnit tests for getNextSequence functionality of the GeneBankFileReader

### ISSUE THREAD

**Issue by ConnorEspino** [ConnorEspino/CS321-003-f21-team-09#17]
As a Developer, I need to write jUnit tests for the "getNextSequnce" functionality of the GeneBankFileReader, so that later when I start writing the actual implementation of the getNextSequence functionality, I will have some confidence that my code is correct.

**Acceptance Criteria:**
- [x] Given a file with no DNA Sequences or improperly formatted information, when trying to call the getNextSequence method, then null is returned. #18
- [x] Given a file that has properly formatted DNA Sequences and the only non-read DNA Sequences are of length n < seqLength, when trying to call getNextSequence again, then null is returned. #19
- [x] Given a file that has properly formatted DNA Sequences and the remaining DNA Sequences are of length n > seqLength, when trying to call getNextSequence, then we should expect no error thrown. #20
- [x] Given a properly formatted file with at least 2 more sequences to be read, when calling getNextSequence twice, then the correct two sequences are returned. #107

**Comment by ConnorEspino** [comment]
Implementation has been merged into master branch

**Comment by ConnorEspino** [comment]
Implementation has been merged into master branch
