### ISSUE TITLE
Write JUnit tests for GeneBankFileReader class constructor functionality

### ISSUE THREAD

**Issue by ConnorEspino** [ConnorEspino/CS321-003-f21-team-09#22]
As a Developer, I need to write jUnit tests for the constructor functionality of the GeneBankFileReader, so that later when I start writing the actual implementation of the constructor functionality, I will have some confidence that my code is correct.

**Acceptance Criteria:**
- [x] Given a non-existent file, when attempting to create a new GeneBankFileReader object, then a FileNotFoundException is thrown. #23
- [x] Given an existing file, when attempting to create a new GeneBankFileReader object, then we should expect no error thrown. #24 
- [x] Given a file with improper DNA Sequence format, when attempting to create a new GeneBankFileReader object, then an InvalidFormatException is thrown. #26

**Comment by ConnorEspino** [comment]
Acceptance criteria has been fulfilled.
