### ISSUE TITLE
Write JUnit tests for the TreeObject class

### ISSUE THREAD

**Issue by ConnorEspino** [ConnorEspino/CS321-003-f21-team-09#49]
As a Developer, I need to write jUnit tests for the TreeObject class.

**Acceptance Criteria:**
- [x] Given a non-null DNASequence, when creating a TreeObject with a value of that DNASequence, then no errors are thrown. #50 

- [x] Given a non-null TreeObject, when calling the getKey() method, then a binary representation of that TreeObject's DNASequence is returned. #51

- [x] Given two non-null, equal TreeObjects (Ex. `AAA` and `AAA`), when calling the equals() method, then 0 is returned. #52
- [x] Given two non-null TreeObjects where the first object has a greater key value than the second (Ex. `TTTT` and `AAAA`), when calling the equals() method, then 1 is returned. #53
- [x] Given two non-null TreeObjects where the second object has a greater key value than the first (Ex. `AAAA` and `TTTT`), when calling the equals() method, then -1 is returned. #54
