### ISSUE TITLE
Write JUnit tests for the BTreeNode class

### ISSUE THREAD

**Issue by ConnorEspino** [ConnorEspino/CS321-003-f21-team-09#63]
As a Developer, I need to write jUnit tests for the TreeObject class.

**Acceptance Criteria:**
- [x] Given a non-null degree, when creating a BTreeNode object, then no errors are thrown. #64 

- [x] Given a non-null, empty BTreeNode object, when inserting a new TreeObject, then no errors are thrown. #65 
- [x] Given a non-null BTreeNode object with multiple elements in it, when inserting a new TreeObject, then no errors are thrown. #66 
- [x] Given a non-null BTreeNode object with multiple elements in it, when inserting a new TreeObject with a value greater than any object in the list, then no errors are thrown. #67 

- [x] Given a non-null BTreeNode object with multiple leaf objects in it, when calling the isLeaf() method, then true is returned. #68 
- [x] Given a non-null BTreeNode object with multiple non-leaf objects in it, when calling the isLeaf() method, then false is returned. #69 

- [x] Given a non-null BTreeNode object with multiple objects in it, when calling the getNumObjects() method, then the number of elements is returned. #70 
- [x] Given a non-null, empty BTreeNode object, when calling the getNumObjects() method, then 0 is returned. #71 

- [x] Given a non-null BTreeNode object with multiple objects in it, when calling the get() method for a valid index, then no errors are thrown. #72 
- [x] Given a non-null BTreeNode object, when calling the get() method for an invalid index, then an IndexOutOfBoundsException is thrown. #73
